### ISSUE TITLE
Separate activitypub.py into stand-alone package?

### ISSUE THREAD

**Issue by dsblank** [tsileo/microblog.pub#1]
Hello! Glad to see this project, and thanks for sharing!

How would you feel about separating out the activitypub components into their own package? Currently, I don't know of a Python package for just the activitypub API, and hate to see developers reinvent the wheel rather than working together. I'd be glad to help.

**Comment by tsileo** [comment]
Hey!

That's definitely something I'm considering, but I feel like it's too early right now, the activitypub code is too tightly coupled to the DB stuff for now (and on purpose, it helps me to iterate more quickly). But it will never be a "general purpose" activtypub library, as I feel it would me way too much work, and I really want to keep the project code base simple.

(a project that I've noticed recently is https://github.com/go-fed/activity, it does more in-depth parsing and is aiming at being a more "general purpose" server, but it's written in go)

At the moment, activities are only interpreted as JSON-LD when dealing with linked data signatures, I did try to play with https://github.com/w3c-social/activipy but it looks like development has stalled, so I'm not sure if microblog.pub will go further about data validation.

Also I really want to have a working tests suite (which I'm already working on) before doing any big changes. But once I feel confident, I will try to use/fill issues on GitHub to help people jump into the project.

So  I think I'll keep the issue open for now.

Let me know if you have any questions, I will take care of your PRs.
Thanks!

**Comment by dsblank** [comment]
Thanks for the feedback! I've been looking and watching the Python-based activitypub repos. You're right: the one you mentioned from w3c-social is not up to date. I agree on getting the tests working first, before pulling apart. Having a clean separation between database (and web server, too) is important to be general purpose, and will take a little work. I'll see if I can pull on what you have so far with the prototype I'm working on here: https://github.com/dsblank/activitypub

**Comment by dsblank** [comment]
It looks like your activitypub is independent of the web app (flask), and, like you say, tightly connected to the database layer (mongo). In making a general activitypub library, a generic database API would be needed. The mongo API looks fairly reasonable to replicate as an abstract interface. Is the database abstraction the only item in what you describe as "too much work" to develop a general activitypub library? Or are there other items that would be major issues?

**Comment by tsileo** [comment]
Hey! I moved the ActivityPub part to a separate project, but it's still far from ready: https://github.com/tsileo/little-boxes

**Comment by dsblank** [comment]
Thanks, I'll be watching :)

**Comment by dsblank** [comment]
@tsileo Thought I'd give you an update and thank you: I've used your little-boxes and microblog.pub (and other libraries) as inspiration for a new module for Python: https://github.com/dsblank/activitypub Thanks, again, for sharing your work!

I thought long about how I'd like to break up the pieces. This is a tricky one! I decided that there are a lot of database pieces ("side-effects" as you say) in microblog.pub that would be nice to have in a core library. A also didn't want developers to have to use MongoDB (even though that choice makes a lot of sense). So, I made a new level, called `Manager` that merges the ActivityPub objects with a database API (mirroring MongoDB's). I'm going to try to put together some sample apps in flask and tornado to demonstrate its use. I'm going to try to mirror microblog.pub with the new library.

**Comment by tsileo** [comment]
Hey!

First thanks for the update. But I feel like you could have mentioned microblog.pub and little-boxes especially as you copied and pasted a lot of code from it (you even left all the `FIXME(tsileo)`). I guess you're planning to re-write everything, but my original code will still be part of the history  the project (and is AGPL 3.0 for microblob.pub and ISC for little-boxes), so I think you're breaking the license terms here.

Anyway thanks for the update and I wish you luck in creating the general AP library you're looking for.

**Comment by dsblank** [comment]
Yes, that code shouldn't have been committed yet, and I will give your projects credit. The LICENSE file is for the activitypub library (and will probably change). The apps are not distributed with the module. I will remove all traces of your code.

**Comment by tsileo** [comment]
No problem! And by the way, I recently created [a Matrix room for microblog.pub](https://matrix.to/#/#microblog.pub:matrix.org), feel free to join if you want to follow development/asking quick questions instead of opening an issue.
Thanks.

**Comment by dsblank** [comment]
There was a errant copy of one of your files and I have deleted it. My bad. Good luck with your project!
