### ISSUE TITLE
Implement Micropub

### ISSUE THREAD

**Issue by zcdunn** [tsileo/microblog.pub#11]
I really like the combination ActivityPub and IndieWeb you're going for with this project. One of your features is providing an API

> Comes with a tiny HTTP API to help posting new content and and read your inbox/notifications

If you haven't interested to much into your own API architecture, I propose you implement [MicroPub](https://indieweb.org/Micropub). MicroPub is an API standard that's a part of the IndieWeb stack. Using it means microblog.pub would be able to use any compliant MicroPub client.

**Comment by tsileo** [comment]
Hi, thanks!

Actually, I had a draft for a MicroPub endpoint that I discarded to focus on the ActivityPub features.

Buy I agree, already having IndieAuth, it's very easy to implement, so I will leave the issue open until I add it back :smile: .

Thanks!

**Comment by tsileo** [comment]
@Serkan-devel in fact microblog.pub is (should?) already be compatible with LitePub (and it's a server to server spec).
Micropub is a client to server protocol, which would let blogging client post new content on microblog.pub.

**Comment by tsileo** [comment]
I will update the README soon, but the support has been pushed, I've tested with few clients and it work well for creating posts. It support media upload, but only the name (converted as summary if present) and the content is parsed (categories and other fields are just dropped).
