### ISSUE TITLE
Boosting a post broke /

### ISSUE THREAD

**Issue by jcgruenhage** [tsileo/microblog.pub#12]
I can't access the root of my microblog anymore since boosting https://mastodon.social/@Gargron/100267642412372290. Unboosting the post does not help. Nothing in the logs of the web container either.

`/liked` also does not work, but it never did for me so ¯\\\_(ツ)\_/¯

**Comment by jcgruenhage** [comment]
Oh wow, it works when being logged out!

**Comment by tsileo** [comment]
Hey!

The `/liked` not working is expected, I just added the link in the header, I did not get the time to finish it yesterday :stuck_out_tongue: ; I will try to use dev branches and keep master "stable".

About the index, I will take a look soon, it might be related to the "delete" button or something like that.

Also, FYI, I will make some breaking changes in the DB soon, but I will try to setup "migration handlers" that will needs to be called manually (by GETting a specific path) for each changes (as I don't want to lose the activities already stored on microblog.pub).

Thanks!

**Comment by jcgruenhage** [comment]
Can't you check the schema version on application startup and do needed migrations then? I totally don't expect a stable thing here, I just hoped the logs would spit out something if it breaks ;D

**Comment by tsileo** [comment]
Should be fixed.
I will think about the schema upgrades, but for the upcoming breaking DB changes it's not only about schema, it's also about merging MongoDB collections, so this one is a little tricky.

I've setup a Matrix room at #microblog.pub I'll put "upgrade" instructions here until a first version is released (and a CHANGELOG started at the same time).

**Comment by tsileo** [comment]
And about the lack of exception, it's because you're running in production mode with errors disabled, with Flask in debug mode, you would get a traceback.

**Comment by jcgruenhage** [comment]
Oh, good to know. Are there any security implications of the debug mode, or can I just run in debug mode all the time? I've joined [the matrix room](https://matrix.to/#/#microblog.pub:matrix.org) btw
