### ISSUE TITLE
Remote Follow doesn't seem to work with Pleroma

### ISSUE THREAD

**Issue by wakest** [tsileo/microblog.pub#15]
I tried it with Mastodon, Misskey and Pleroma and Pleroma is the only one that seemingly doesn't work

it directed me to https://cathoderay.tube/ostatus_subscribe?acct=dev@microblog.pub which doesn't seem to exist.

**Comment by tsileo** [comment]
Thanks for for the report!
I will take a look.

**Comment by tsileo** [comment]
I started to take a look, actually the page is returning an error 500, and it seems to work with a Mastodon account as `acct`.

Looks like Pleroma is expecting the host to have a valid OStatus atom feed (it's not part of ActivityPub, neither is the remote follow stuff, it's gathered from OStatus).

I will look if exporting the feed is enough to make Pleroma happy, or I will open an issue on their side.
