### ISSUE TITLE
Improper redirect making a new post goes to localhost not the FQDN

### ISSUE THREAD

**Issue by mitchellurgero** [tsileo/microblog.pub#25]
When I login, as well as make a new post upon completion of these tasks the backend sends me to `localhost:5005` and not `https://example.com` as set in the me.yml file.

Edit 1: I should note, I am using Caddy proxy to reach the application

**Comment by jcgruenhage** [comment]
Are you using the `transparent` preset of caddy's proxy directive?

Something like that?
```
proxy / localhost:5005 {
    transparent
}
```

**Comment by mitchellurgero** [comment]
I am using:

```
example.com {
    proxy / localhost:5005
}
```

/admin/notifications works for me just fine however.

**Comment by tsileo** [comment]
@jcgruenhage is right (thanks!), the issue is coming from your reverse proxy settings, all the redirect are HTTP redirects with a relative path, localhost is never hard-coded in the app.
