### ISSUE TITLE
Mastodon Mobile Client Support?

### ISSUE THREAD

**Issue by mitchellurgero** [tsileo/microblog.pub#27]
As the title reads?

**Comment by tsileo** [comment]
Hey!

This project is "ActivityPub first".

Mastodon does not implements the ActivityPub Client/Server API (only the federation Server/Server API). It uses its custom API, some projects are re-implementing it, but I feel doing it would be going backward, I don't want to spend time working on a re-implementing the Mastodon client API.

I tried to look for "ActivityPub" mobile client, but I haven't found one yet (if you find one, please do share it :stuck_out_tongue: ).
The plan is to have 3 different options to interact with microblog.pub:
 - the "standardized" ActivityPub Client/Server API (I haven't found a great mobile client yet, I may work on a tiny one using Flutter)
 - The "tiny" REST API that the admin UI is using (and documented on the README)
 - Using the Micropub endpoints (see #11 ), which another W3C standard as ActivityPub.

So I'm closing this a won't fix.

Thanks.

**Comment by mitchellurgero** [comment]
Is your code modular? Cause i'll make the endpoints in a module/plugin/addon and maintain it myself.

**Comment by tsileo** [comment]
The project is still in early development, so no the code is not super modular yet.

As a reminder, the goal of the project is to expose a simple ActivityPub server as a microblog, the Mastodon compatibility is a side-effect, so I won't merge extra features required for the Mastodon API compatibility.

But I will be glad to help supporting external "module/plugin/addon" once you have something.

**Comment by mitchellurgero** [comment]
I can do the Mastodon API, I just need a module/plugin system and I can get it started.

**Comment by mitchellurgero** [comment]
So let me know when/if you are doing that :)

**Comment by beta-phenylethylamine** [comment]
It's notable that you could absolute write a light middleware that you connect to and it connects to the microblog.pub server that basically just translates the API and just run them of the same server. You could even probably chose not to expose the ActivityPub C2S API by just fiddling around with nginx a little to block POST requests to outboxes if i had to guess

**Comment by beta-phenylethylamine** [comment]
I'm actually currently working on my own "generic AP server" that just implements AP C2S and S2S (with some extensions, but no incompatibility), but more as a backend server that's used by a frontend server to federate, and my plan is to have the frontend servers really implement their own APIs and all if they want to but also have it possible to connect directly to the backend server if you really want to
