### ISSUE TITLE
Replying to Mastodon account broken?

### ISSUE THREAD

**Issue by mitchellurgero** [tsileo/microblog.pub#29]
This seems to happen on almost any note I try to post:

`"\"https://example.com/followers\" is invalid"` 

I'd also like to note this is still using Caddy  with the following configuration:

```
example.com {
        proxy / localhost:5005 {
                transparent
        }
}

```

Am I missing another thing or is this broken in the latest commit? Also this does break federation in some areas. I cannot communicate with another test account on another server.

**Comment by tsileo** [comment]
It works for me! This is not a bug report, how can I reproduce this?
And what do you mean by "break federation in some areas"?

This is not a useful report, and you cannot run it and expect everything to work, I already warned you!

**Comment by mitchellurgero** [comment]
> and you cannot run it and expect everything to work

But it works for you is my point. It was just a standard install with Caddy - nothing fancy. No modifications, on the commit 11ad9ec10a956a385373fd273a05551ef691b9c3.

Python3 is installed, Latest Caddy is used with the configuration above. It could be specific to my system I do not know.

Ubuntu 18.04 is the OS. and I can recreate the issue every time I fresh install. If you can tell me where to access logs for microblog I can give you a proper bug report.

**Comment by jcgruenhage** [comment]
@mitchellurgero I also have a standard install with Caddy, with a very similar proxy configuration, it works fine for me. You can get the logs by running `docker-compose logs`. @tsileo, can you tell us how exactly to enable the debug mode, for better logs?

**Comment by tsileo** [comment]
The thing is I'm working on improving the logs!

**Comment by mitchellurgero** [comment]
@jcgruenhage Thanks bud, it's possible it's my server configuration outside of Caddy + Microblog (like docker maybe?)

**Comment by tsileo** [comment]
Nope, `make dev` is just for running MongoDB and the Celery worker.

**Comment by mitchellurgero** [comment]
See EDIT.

**Comment by tsileo** [comment]
Same, I mean I wrote the Makefile...

**Comment by tsileo** [comment]
As I said I'm working on the logs, I will try to update the README once it's improved.

BTW, for "dev"/running dev instance, I think it would be easier to talk in the Matrix room: https://riot.im/app/#/room/#microblog.pub:matrix.org

**Comment by mitchellurgero** [comment]
I am joined there, I'll keep an eye out. Thanks for your hard work!
