### ISSUE TITLE
UI links for older/newer are swapped

### ISSUE THREAD

**Issue by dsblank** [tsileo/microblog.pub#32]
I believe that the links "Older"/"Newer" are swapped, and maybe on the wrong sides:

![screenshot from 2018-07-19 01-03-14](https://user-images.githubusercontent.com/168568/42922735-05ee586c-8af0-11e8-91dd-bbbadc5c649f.png)

Clicking the above "Newer" will show the oldest note, number 1.

**Comment by tsileo** [comment]
How did you get to this point? On my instance and locally, I cannot reproduce it (on the homepage and in the stream).

**Comment by dsblank** [comment]
Sorry, my bad! I have re-implemented your use of pymongo as an abstraction (to allow other database backends) and had swapped $lt and $gt.
