### ISSUE TITLE
Deleting from the permalink page gives 410 error

### ISSUE THREAD

**Issue by dsblank** [tsileo/microblog.pub#33]
Gives a 410 error, which is correct, but probably don't need to see this:

## Gone

`The requested URL is no longer available on this server and there is no forwarding address. If you followed a link from a foreign page, please contact the author of this page.`

Suggest heading back to main page.

**Comment by tsileo** [comment]
For now, I made sure the API is returning a Tombstone object when JSON-LD is required, but I haven't setup any custom error pages yet for the "public website". I'm closing this and I'm creating an issue to track the custom error pages.
