### ISSUE TITLE
Ability to remote follow via Plemora?

### ISSUE THREAD

**Issue by buoyantair** [tsileo/microblog.pub#40]
Currently Plemora users can remote-follow users from other plemora instances and mastodon instances. I think it would be nice to have the ability to remote follow users on microblog instances via plemora and vice versa.

What do you guys think?

**Comment by buoyantair** [comment]
Awesome! This is going to be a very handy feature for me <3

**Comment by tsileo** [comment]
Hey!

I've already started digging into this, I'm not 100% it will be possible, as Mastodon/Pleroma support OStatus (and microblog.pub is ActivityPub only), and the remote follow is OStatus related. I added the necessary stubs to make it work with Mastodon, but I cannot get it to work with Pleroma, but it's been a while, so maybe things changed.

I think by searching the profile URL or a note URL, you should already be able to follow a microblog.pub instance already (and it wasn't the case when #15 was opened).

I will take a look at this soon and update the issues accordingly, thanks!

**Comment by buoyantair** [comment]
@tsileo Awesome!
