### ISSUE TITLE
Site down?

### ISSUE THREAD

**Issue by petrk94** [tsileo/microblog.pub#41]
Hello,
Im trying to see the example website running, but I get always connection refused.
Is the project dead?

Thanks

**Comment by cwt** [comment]
However please note that my site is running the modified theme and code from this fork on arm64 branch https://github.com/bashell-com/microblog.pub

So the look and feel already changed from the original site.

**Comment by petrk94** [comment]
ah I see, but it give at least a feel about it :) 
Thanks
