### ISSUE TITLE
twemoji embedding contradicts the no-JS policy

### ISSUE THREAD

**Issue by JustAnotherArchivist** [tsileo/microblog.pub#48]
A key feature of μblog.pub, given how it's highlighted in the readme, is that it does not use any JavaScript. Let me just say that I very much appreciate that; it's rare nowadays to see well-designed, functional services that don't rely on JS to work (or even display anything at all).

However, every page actually embeds twemoji:

https://github.com/tsileo/microblog.pub/blob/713eb6acac63e826d71f1475746a9aaad405d466/templates/layout.html#L46-L55

While this does not seem to affect the usability with disabled JS in any way, it still goes against the spirit of not using any JS.

**Comment by tsileo** [comment]
Hey! Thank you for the feedback!

You made me realize I should be able to replace twemoji by something like https://pypi.org/project/emojificate/ ; I will take a look.

And as you said, it was added only because it does not affect usability at all (unicode emojis are displayed instead of the images).

I will keep you updated!

**Comment by JustAnotherArchivist** [comment]
That looks interesting. Too bad that the CDN appears to be hardcoded, so you can't self-host it (unless you monkey-patch emojificate). It's also marked as alpha and doesn't support zero-width joins. Without looking very much into it, https://github.com/nitely/emoji-unicode might be an alternative.

**Comment by tsileo** [comment]
`emoji-unicode` looked better indeed :+1: 
Thanks @JustAnotherArchivist!

**Comment by JustAnotherArchivist** [comment]
Great to hear, thank you! :+1:

**Comment by JustAnotherArchivist** [comment]
@tsileo Quick follow-up, could you make `EMOJI` configurable so that it's possible to self-host the images without code modifications?

**Comment by tsileo** [comment]
Done! (I thought about it but was too lazy :stuck_out_tongue:)

**Comment by JustAnotherArchivist** [comment]
Excellent, thank you!

(For reference, that's 0f6fa36f.)
