### ISSUE TITLE
Add compatibility with Plume

### ISSUE THREAD

**Issue by marek-lach** [tsileo/microblog.pub#49]
The way I understand it, microblog.pub can currently discover users only by the following format of the URL: instance.name/@username 

However, there’s some ActivityPub software, like the blogging platform Plume, which discovers users in this profile URL format:
instance.name/@/username

Software like Mastodon, Friendica, or Pleroma have a webfinger implementation that can understand both of these formats, for the utmost compatibility between various AP software.

Can you look into supporting this with microblog.pub?

Thanks,

**Comment by tsileo** [comment]
Hey,

microblog.pub is already compatible with Plume (I've tested it manually in the past), and you can lookup any AP object either via the URL (actor or any content) or using `@username@domain.tld` (regular webfinger like all AP software). And microblog.pub has support for displaying `Article`.

I will add mention Plume in the README.

Thanks.

**Comment by marek-lach** [comment]
Right. Great. For clarification, if I understand things correctly: when trying to remote follow a microblog.pub server like bellow:

<img width="1280" alt="Screenshot 2019-05-10 at 23 05 26" src="https://user-images.githubusercontent.com/45913977/57556964-bca96a80-7378-11e9-812a-da996263f09a.png">

with a Plume instance, I see the following:

<img width="1280" alt="Screenshot 2019-05-10 at 23 05 12" src="https://user-images.githubusercontent.com/45913977/57556999-d64ab200-7378-11e9-99d2-59b24495e8a5.png">

Does this simply imply a temporary server overload, or something like that?

The reason I ask, is because I was getting the same error, when trying to remote follow your blog with my Misskey account, but now, later in the day, it seems to work just fine with Misskey.

**Comment by tsileo** [comment]
Hey, thanks for the details. I misinterpreted your questions, I thought about following a Plume account from microblog.pub (which works well), and not about a Plume account following a microblog.pub one.

It should not be a temporary error (looking at the screenshot, it looks like Plume is returning a "relative path" wehereas microblog.pub expects a absolute, but it's just a guess).

I will take a look and keep you updated, thanks!

**Comment by tsileo** [comment]
It looks like the issue is on Plume side, it returns the "follow template URL" without any scheme:

```python
In [2]: from little_boxes import webfinger

In [3]: webfinger.get_remote_follow_template("@mareklach@fediverse.blog")
Out[3]: 'fediverse.blog/remote_interact?{uri}'

In [4]: webfinger.get_remote_follow_template("@kaniini@pleroma.site")
Out[4]: 'https://pleroma.site/ostatus_subscribe?acct={uri}'

In [5]: webfinger.get_remote_follow_template("@rinsuki@misskey.xyz")
Out[5]: 'https://misskey.xyz/authorize-follow?acct={uri}'

In [6]: webfinger.get_remote_follow_template("@Gargron@mastodon.social")
Out[6]: 'https://mastodon.social/authorize_interaction?uri={uri}'
```

I will make a quick hack, but all other software are returning the scheme, maybe Plume should do the same, can you open an issue in Plume repo?
