### ISSUE TITLE
Password key is expected to be "pass"

### ISSUE THREAD

**Issue by taziden** [tsileo/microblog.pub#51]
https://github.com/tsileo/microblog.pub/blob/766678fb8f416f54e8b88dd25693d9cc7c38b5e5/setup_wizard/wizard.py#L31

According to config.py, the key associated to the password is expected to be "pass" not "password":
https://github.com/tsileo/microblog.pub/blob/766678fb8f416f54e8b88dd25693d9cc7c38b5e5/config.py#L70

**Comment by tsileo** [comment]
Oops! Thanks for reporting!
