### ISSUE TITLE
setup.py for easy installation

### ISSUE THREAD

**Issue by arunisaac** [tsileo/microblog.pub#60]
Hi,

I would like to package microblog.pub for Guix, a GNU/Linux distribution. It would help if you could provide a setup.py so that microblog.pub can be installed easily using the conventional `python setup.py install`.

Thanks, and great work!

**Comment by tsileo** [comment]
Hey, sorry for the late response.

I don't consider the project is a Python package per se, there's dependencies on 2 external processes, and the extra "wizard step".

The "official"/supported (by me) way to run the project is to use docker-compose.

Feel free to fork it with just a setup.py or an extra repo for managing that, if you do it I will be glad to link it from this repo.

Thanks!
