### ISSUE TITLE
Approving followers

### ISSUE THREAD

**Issue by N07070** [tsileo/microblog.pub#61]
Hello,

It would be nice to be able to post notes to only a list of approved followers, or implement a sort of "private blog" functionality, where you can approve the followers of your blog.

Sort of a privacy level setting for posts, like on Mastodon.

I could help with the implementation if needed.

**Comment by tsileo** [comment]
Hey, the option for posting to the "followers only" audience is already there.

What is missing is the "manually approves followers" setting, I will try to implement it today as some parts are already there.

Thank you!

**Comment by N07070** [comment]
Awesome, thanks !
