### ISSUE TITLE
Workaround for humanitarians

### ISSUE THREAD

**Issue by autogestion** [tsileo/microblog.pub#7]
What can be done to make possible for non-technical people, just upload some package on amazon, hit "launch" and get a blog?

**Comment by tsileo** [comment]
Hey,

The project is still in early development, it's too early to think about these things.

Everything is manager by Docker/docker-compose, in the future it should be easy to build integration like "deploy to this VPS cloud provider".

I'm closing the issue but adding this to my "long-term" todo list.

Thanks!
