### ISSUE TITLE
possible that I'm not getting all posts?

### ISSUE THREAD

**Issue by seekr** [tsileo/microblog.pub#71]
I don't know the exactly rules of federation specially when it involves boosting and replying to notes from other instances but I think I'm not getting all posts from the people I follow.

When I compare my mastodon.social stream to the stream in microblog.pub I see far fewer posts in my microblog.pub stream.

Is it possible that I'm not getting everything?

**Comment by tsileo** [comment]
Hi,

I think the difference is that Mastodon show replies of people you follow (i.e. A reply to B, and you follow both A and B, then it will show in your timeline).

Microblog.pub does not show replies (but it does store them and show the number of replies below posts).
