### ISSUE TITLE
A way to clean the database

### ISSUE THREAD

**Issue by pvdosev** [tsileo/microblog.pub#90]
I started following some prolific accounts, that share lots of images. The database is quickly ballooning in size, it's up to 4 gigs in just a week. Is there a way to clean up my inbox, maybe before a particular date?

**Comment by tsileo** [comment]
Hey, there's a task that performs a cleanup (and is run every 1 hour).
You can tweak the `days_to_keep` config item (which is 14 days by default).

**Comment by pvdosev** [comment]
Oh great, that makes sense. I noticed that it stopped growing. Thank you!
